# Generated by Django 5.1.5 on 2025-01-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_claim_date_alter_researchpaper_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='trust_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
