# Generated by Django 5.1.5 on 2025-01-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_claim_category_alter_claim_counter_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
