# Generated by Django 5.1.5 on 2025-01-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_influencer_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
