# Generated by Django 5.1.5 on 2025-01-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_influencer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkresearch',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claimresearch',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='singleresearch',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
