# Generated by Django 5.1.5 on 2025-01-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_bulkresearch_failed_claimresearch_failed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
