# Generated by Django 5.1.5 on 2025-01-28 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkresearch',
            name='influencers',
            field=models.ManyToManyField(blank=True, related_name='bulk_researches', to='core.influencer'),
        ),
        migrations.AlterField(
            model_name='claimresearch',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_researches', to='core.claim'),
        ),
        migrations.AlterField(
            model_name='singleresearch',
            name='influencer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_researches', to='core.influencer'),
        ),
    ]
